### ISSUE TITLE
Use `prefer-stable: true` in composer.json

### ISSUE THREAD

**Issue by dhensby** [silverstripe/platform-project#11]
Rather than declaring each package should be stable, better to add [`"prefer-stable": true`](https://getcomposer.org/doc/04-schema.md#prefer-stable) to the `composer.json` as it'll seek out a stable version first and only use a dev package if no other matching release can be found.

**Comment by andrewandante** [comment]
I am a scrub and wrote the word `Issue` so this didn't auto-close. :disappointed:
